import csv

# ============================================================
# CONFIG
# ============================================================

OUTPUT_FILE = "loan_products.csv"

CREATED_AT = "2026-08-13 22:00:00"
UPDATED_AT = "2026-08-13 22:00:00"

TEXT_DEFAULT = "Not Applicable"
NUM_DEFAULT = 0
BOOL_DEFAULT = "No"


# ============================================================
# LOAN PRODUCT CREATOR
# ============================================================

def create_loan(
    loan_product_id,
    product_code,
    product_name,
    loan_category,
    loan_subcategory,
    loan_type,

    customer_type="Individual",
    secured_or_unsecured="Unsecured",
    product_status="Active",
    product_description="HDFC-style lending product for prototype use.",

    loan_purpose="General financing",
    allowed_purposes="General financing",
    end_use_restriction="Standard bank policy",
    asset_financing="No",
    working_capital_financing="No",
    refinancing_available="No",
    balance_transfer_available="No",
    top_up_available="No",
    additional_loan_available="No",

    minimum_loan_amount=50000,
    maximum_loan_amount=2500000,
    minimum_loan_amount_online=50000,
    maximum_loan_amount_online=2500000,
    minimum_down_payment=0,
    maximum_financing_percentage=90,
    loan_to_value_ratio=0,
    margin_requirement=10,

    minimum_tenure_months=12,
    maximum_tenure_months=60,
    typical_tenure_months=36,
    repayment_frequency="Monthly",
    grace_period_days=0,
    moratorium_period_months=0,

    interest_rate_type="Floating",
    interest_rate_min=10.50,
    interest_rate_max=18.00,
    interest_rate_current=12.50,
    annual_percentage_rate=13.50,
    benchmark_rate="Bank benchmark / internal pricing",
    spread=2.50,
    fixed_rate_available="Yes",
    floating_rate_available="Yes",
    rate_reset_frequency="Monthly / As specified",

    processing_fee_type="Percentage",
    processing_fee_value=1.00,
    processing_fee_min=500,
    processing_fee_max=5000,
    prepayment_allowed="Yes",
    prepayment_charge_type="Percentage",
    prepayment_charge=3.00,
    foreclosure_allowed="Yes",
    foreclosure_charge=3.00,
    part_payment_allowed="Yes",
    part_payment_charge=0,
    late_payment_fee=500,
    bounce_charge=500,
    penal_interest=2.00,
    documentation_charge=500,
    stamp_duty_charge=100,
    valuation_charge=0,
    legal_charge=0,
    insurance_charge=0,
    other_charges="Applicable taxes and statutory charges",

    minimum_age=21,
    maximum_age=60,
    minimum_age_at_maturity=65,
    maximum_age_at_maturity=70,
    residential_requirement="Indian Resident",
    citizenship_requirement="Indian Citizen",
    employment_type="Salaried / Self-employed",
    allowed_employment_types="Salaried, Self-employed",
    minimum_work_experience_months=12,
    minimum_business_vintage_months=0,
    minimum_income_monthly=25000,
    minimum_income_annual=300000,
    minimum_turnover=0,
    minimum_net_profit=0,
    minimum_credit_score=700,
    credit_history_required="Yes",
    existing_customer_required="No",
    bank_account_required="Yes",
    relationship_duration_required_months=0,

    co_applicant_allowed="Yes",
    co_applicant_required="No",
    minimum_co_applicants=0,
    maximum_co_applicants=1,
    guarantor_required="No",
    acceptable_co_applicant_relationships="Spouse / Parent / Family member",
    co_applicant_income_considered="Yes",

    salaried_eligible="Yes",
    self_employed_eligible="Yes",
    business_owner_eligible="Yes",
    professional_eligible="Yes",
    government_employee_eligible="Yes",
    retired_eligible="No",
    student_eligible="No",
    minimum_employment_months=12,
    minimum_business_vintage_years=2,
    income_document_required="Yes",
    bank_statement_months_required=6,
    salary_slip_months_required=3,
    itr_years_required=2,

    credit_score_required="Yes",
    maximum_dti_ratio=50,
    maximum_foir_ratio=50,
    existing_loan_allowed="Yes",
    existing_loan_limit="Subject to eligibility",
    credit_card_history_required="No",
    delinquency_allowed="No",
    maximum_recent_enquiries=5,

    collateral_required="No",
    collateral_type="Not Applicable",
    security_type="Not Applicable",
    hypothecation_required="No",
    mortgage_required="No",
    pledge_required="No",
    lien_required="No",
    guarantee_required="No",
    collateral_value_required=0,
    collateral_valuation_method="Not Applicable",

    identity_proof_required="Yes",
    address_proof_required="Yes",
    income_proof_required="Yes",
    bank_statement_required="Yes",
    salary_slip_required="Yes",
    itr_required="Yes",
    employment_proof_required="Yes",
    business_proof_required="No",
    property_document_required="No",
    vehicle_document_required="No",
    gold_document_required="No",
    education_document_required="No",
    collateral_document_required="No",
    other_documents="PAN, KYC and bank-specific documents",

    disbursement_mode="Bank Account Transfer",
    disbursement_account_required="Yes",
    minimum_disbursement_amount=50000,
    maximum_disbursement_amount=2500000,
    full_disbursement_allowed="Yes",
    partial_disbursement_allowed="No",
    multiple_disbursement_allowed="No",
    estimated_disbursement_time="1-3 working days",

    emi_available="Yes",
    emi_frequency="Monthly",
    emi_start_month=1,
    repayment_method="EMI",
    auto_debit_available="Yes",
    nach_available="Yes",
    ecs_available="Yes",
    digital_repayment_available="Yes",
    advance_emi_allowed="Yes",
    moratorium_available="No",

    asset_type="Not Applicable",
    vehicle_type="Not Applicable",
    vehicle_condition="Not Applicable",
    property_type="Not Applicable",
    property_location_requirement="Not Applicable",
    education_level="Not Applicable",
    education_country="Not Applicable",
    institution_type="Not Applicable",
    course_type="Not Applicable",
    gold_purity_requirement=0,
    gold_valuation_method="Not Applicable",
    business_sector="Not Applicable",
    agriculture_activity="Not Applicable",
    commercial_vehicle_type="Not Applicable",
    construction_equipment_type="Not Applicable",

    digital_application_available="Yes",
    instant_approval_available="Yes",
    pre_approved_available="Yes",
    paperless_processing="Yes",
    doorstep_service="Yes",
    relationship_manager_service="Yes",
    flexible_repayment="Yes",
    step_up_emi_available="No",
    step_down_emi_available="No",
    balloon_payment_available="No",
    seasonal_repayment_available="No",
    tax_benefit_available="No",
    insurance_bundle_available="No",
    special_rate_available="Yes",
    promotional_offer_available="Yes",

    tag_personal=0,
    tag_home=0,
    tag_vehicle=0,
    tag_two_wheeler=0,
    tag_education=0,
    tag_travel=0,
    tag_medical=0,
    tag_business=0,
    tag_agriculture=0,
    tag_gold=0,
    tag_property=0,
    tag_investment=0,
    tag_emergency=0,
    tag_small_business=0,
    tag_professional=0,
    tag_nri=0,
    tag_premium=0,
    tag_digital=1,
    tag_quick_disbursal=0,
    tag_low_documentation=0,
    tag_high_value=0,

    launch_date="2020-01-01",
    end_date="2099-12-31"
):
    return {
        "loan_product_id": loan_product_id,
        "product_code": product_code,
        "product_name": product_name,
        "loan_category": loan_category,
        "loan_subcategory": loan_subcategory,
        "loan_type": loan_type,
        "customer_type": customer_type,
        "secured_or_unsecured": secured_or_unsecured,
        "product_status": product_status,
        "product_description": product_description,

        "loan_purpose": loan_purpose,
        "allowed_purposes": allowed_purposes,
        "end_use_restriction": end_use_restriction,
        "asset_financing": asset_financing,
        "working_capital_financing": working_capital_financing,
        "refinancing_available": refinancing_available,
        "balance_transfer_available": balance_transfer_available,
        "top_up_available": top_up_available,
        "additional_loan_available": additional_loan_available,

        "minimum_loan_amount": minimum_loan_amount,
        "maximum_loan_amount": maximum_loan_amount,
        "minimum_loan_amount_online": minimum_loan_amount_online,
        "maximum_loan_amount_online": maximum_loan_amount_online,
        "minimum_down_payment": minimum_down_payment,
        "maximum_financing_percentage": maximum_financing_percentage,
        "loan_to_value_ratio": loan_to_value_ratio,
        "margin_requirement": margin_requirement,

        "minimum_tenure_months": minimum_tenure_months,
        "maximum_tenure_months": maximum_tenure_months,
        "typical_tenure_months": typical_tenure_months,
        "repayment_frequency": repayment_frequency,
        "grace_period_days": grace_period_days,
        "moratorium_period_months": moratorium_period_months,

        "interest_rate_type": interest_rate_type,
        "interest_rate_min": interest_rate_min,
        "interest_rate_max": interest_rate_max,
        "interest_rate_current": interest_rate_current,
        "annual_percentage_rate": annual_percentage_rate,
        "benchmark_rate": benchmark_rate,
        "spread": spread,
        "fixed_rate_available": fixed_rate_available,
        "floating_rate_available": floating_rate_available,
        "rate_reset_frequency": rate_reset_frequency,

        "processing_fee_type": processing_fee_type,
        "processing_fee_value": processing_fee_value,
        "processing_fee_min": processing_fee_min,
        "processing_fee_max": processing_fee_max,
        "prepayment_allowed": prepayment_allowed,
        "prepayment_charge_type": prepayment_charge_type,
        "prepayment_charge": prepayment_charge,
        "foreclosure_allowed": foreclosure_allowed,
        "foreclosure_charge": foreclosure_charge,
        "part_payment_allowed": part_payment_allowed,
        "part_payment_charge": part_payment_charge,
        "late_payment_fee": late_payment_fee,
        "bounce_charge": bounce_charge,
        "penal_interest": penal_interest,
        "documentation_charge": documentation_charge,
        "stamp_duty_charge": stamp_duty_charge,
        "valuation_charge": valuation_charge,
        "legal_charge": legal_charge,
        "insurance_charge": insurance_charge,
        "other_charges": other_charges,

        "minimum_age": minimum_age,
        "maximum_age": maximum_age,
        "minimum_age_at_maturity": minimum_age_at_maturity,
        "maximum_age_at_maturity": maximum_age_at_maturity,
        "residential_requirement": residential_requirement,
        "citizenship_requirement": citizenship_requirement,
        "employment_type": employment_type,
        "allowed_employment_types": allowed_employment_types,
        "minimum_work_experience_months": minimum_work_experience_months,
        "minimum_business_vintage_months": minimum_business_vintage_months,
        "minimum_income_monthly": minimum_income_monthly,
        "minimum_income_annual": minimum_income_annual,
        "minimum_turnover": minimum_turnover,
        "minimum_net_profit": minimum_net_profit,
        "minimum_credit_score": minimum_credit_score,
        "credit_history_required": credit_history_required,
        "existing_customer_required": existing_customer_required,
        "bank_account_required": bank_account_required,
        "relationship_duration_required_months":
            relationship_duration_required_months,

        "co_applicant_allowed": co_applicant_allowed,
        "co_applicant_required": co_applicant_required,
        "minimum_co_applicants": minimum_co_applicants,
        "maximum_co_applicants": maximum_co_applicants,
        "guarantor_required": guarantor_required,
        "acceptable_co_applicant_relationships":
            acceptable_co_applicant_relationships,
        "co_applicant_income_considered":
            co_applicant_income_considered,

        "salaried_eligible": salaried_eligible,
        "self_employed_eligible": self_employed_eligible,
        "business_owner_eligible": business_owner_eligible,
        "professional_eligible": professional_eligible,
        "government_employee_eligible": government_employee_eligible,
        "retired_eligible": retired_eligible,
        "student_eligible": student_eligible,
        "minimum_employment_months": minimum_employment_months,
        "minimum_business_vintage_years": minimum_business_vintage_years,
        "income_document_required": income_document_required,
        "bank_statement_months_required": bank_statement_months_required,
        "salary_slip_months_required": salary_slip_months_required,
        "itr_years_required": itr_years_required,

        "credit_score_required": credit_score_required,
        "maximum_dti_ratio": maximum_dti_ratio,
        "maximum_foir_ratio": maximum_foir_ratio,
        "existing_loan_allowed": existing_loan_allowed,
        "existing_loan_limit": existing_loan_limit,
        "credit_card_history_required": credit_card_history_required,
        "delinquency_allowed": delinquency_allowed,
        "maximum_recent_enquiries": maximum_recent_enquiries,

        "collateral_required": collateral_required,
        "collateral_type": collateral_type,
        "security_type": security_type,
        "hypothecation_required": hypothecation_required,
        "mortgage_required": mortgage_required,
        "pledge_required": pledge_required,
        "lien_required": lien_required,
        "guarantee_required": guarantee_required,
        "collateral_value_required": collateral_value_required,
        "collateral_valuation_method": collateral_valuation_method,

        "identity_proof_required": identity_proof_required,
        "address_proof_required": address_proof_required,
        "income_proof_required": income_proof_required,
        "bank_statement_required": bank_statement_required,
        "salary_slip_required": salary_slip_required,
        "itr_required": itr_required,
        "employment_proof_required": employment_proof_required,
        "business_proof_required": business_proof_required,
        "property_document_required": property_document_required,
        "vehicle_document_required": vehicle_document_required,
        "gold_document_required": gold_document_required,
        "education_document_required": education_document_required,
        "collateral_document_required":
            collateral_document_required,
        "other_documents": other_documents,

        "disbursement_mode": disbursement_mode,
        "disbursement_account_required": disbursement_account_required,
        "minimum_disbursement_amount": minimum_disbursement_amount,
        "maximum_disbursement_amount": maximum_disbursement_amount,
        "full_disbursement_allowed": full_disbursement_allowed,
        "partial_disbursement_allowed": partial_disbursement_allowed,
        "multiple_disbursement_allowed":
            multiple_disbursement_allowed,
        "estimated_disbursement_time":
            estimated_disbursement_time,

        "emi_available": emi_available,
        "emi_frequency": emi_frequency,
        "emi_start_month": emi_start_month,
        "repayment_method": repayment_method,
        "auto_debit_available": auto_debit_available,
        "nach_available": nach_available,
        "ecs_available": ecs_available,
        "digital_repayment_available":
            digital_repayment_available,
        "advance_emi_allowed": advance_emi_allowed,
        "moratorium_available": moratorium_available,

        "asset_type": asset_type,
        "vehicle_type": vehicle_type,
        "vehicle_condition": vehicle_condition,
        "property_type": property_type,
        "property_location_requirement":
            property_location_requirement,
        "education_level": education_level,
        "education_country": education_country,
        "institution_type": institution_type,
        "course_type": course_type,
        "gold_purity_requirement": gold_purity_requirement,
        "gold_valuation_method": gold_valuation_method,
        "business_sector": business_sector,
        "agriculture_activity": agriculture_activity,
        "commercial_vehicle_type":
            commercial_vehicle_type,
        "construction_equipment_type":
            construction_equipment_type,

        "digital_application_available":
            digital_application_available,
        "instant_approval_available":
            instant_approval_available,
        "pre_approved_available":
            pre_approved_available,
        "paperless_processing": paperless_processing,
        "doorstep_service": doorstep_service,
        "relationship_manager_service":
            relationship_manager_service,
        "flexible_repayment": flexible_repayment,
        "step_up_emi_available":
            step_up_emi_available,
        "step_down_emi_available":
            step_down_emi_available,
        "balloon_payment_available":
            balloon_payment_available,
        "seasonal_repayment_available":
            seasonal_repayment_available,
        "tax_benefit_available":
            tax_benefit_available,
        "insurance_bundle_available":
            insurance_bundle_available,
        "special_rate_available":
            special_rate_available,
        "promotional_offer_available":
            promotional_offer_available,

        "tag_personal": tag_personal,
        "tag_home": tag_home,
        "tag_vehicle": tag_vehicle,
        "tag_two_wheeler": tag_two_wheeler,
        "tag_education": tag_education,
        "tag_travel": tag_travel,
        "tag_medical": tag_medical,
        "tag_business": tag_business,
        "tag_agriculture": tag_agriculture,
        "tag_gold": tag_gold,
        "tag_property": tag_property,
        "tag_investment": tag_investment,
        "tag_emergency": tag_emergency,
        "tag_small_business": tag_small_business,
        "tag_professional": tag_professional,
        "tag_nri": tag_nri,
        "tag_premium": tag_premium,
        "tag_digital": tag_digital,
        "tag_quick_disbursal": tag_quick_disbursal,
        "tag_low_documentation": tag_low_documentation,
        "tag_high_value": tag_high_value,

        "launch_date": launch_date,
        "end_date": end_date,
        "created_at": CREATED_AT,
        "updated_at": UPDATED_AT
    }


# ============================================================
# LOAN PRODUCT CATALOGUE
# ============================================================

loans = [

    # ========================================================
    # PERSONAL
    # ========================================================

    create_loan(
        "LN001",
        "HDFC_PERSONAL_LOAN",
        "Personal Loan",
        "Personal",
        "Unsecured Personal Loan",
        "Personal Loan",

        loan_purpose="Personal financial requirements",
        allowed_purposes="Travel, medical, wedding, education, home improvement, emergencies",
        minimum_loan_amount=50000,
        maximum_loan_amount=4000000,
        minimum_loan_amount_online=50000,
        maximum_loan_amount_online=4000000,
        minimum_tenure_months=12,
        maximum_tenure_months=60,
        typical_tenure_months=36,
        interest_rate_min=10.50,
        interest_rate_max=24.00,
        interest_rate_current=13.00,
        annual_percentage_rate=14.00,
        processing_fee_value=1.50,
        processing_fee_min=999,
        processing_fee_max=7500,
        prepayment_charge=4,
        foreclosure_charge=4,
        minimum_income_monthly=30000,
        minimum_income_annual=360000,
        minimum_credit_score=700,
        collateral_required="No",
        digital_application_available="Yes",
        instant_approval_available="Yes",
        pre_approved_available="Yes",
        paperless_processing="Yes",
        tag_personal=1,
        tag_travel=1,
        tag_medical=1,
        tag_emergency=1,
        tag_digital=1,
        tag_quick_disbursal=1
    ),

    # ========================================================
    # HOME
    # ========================================================

    create_loan(
        "LN002",
        "HDFC_HOME_LOAN",
        "Home Loan",
        "Home",
        "Residential Home Loan",
        "Home Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase, construction or renovation of residential property",
        allowed_purposes="Purchase of home, construction, extension, renovation",
        asset_financing="Yes",
        balance_transfer_available="Yes",
        top_up_available="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=100000000,
        minimum_loan_amount_online=500000,
        maximum_loan_amount_online=100000000,
        minimum_down_payment=10,
        maximum_financing_percentage=90,
        loan_to_value_ratio=90,
        margin_requirement=10,
        minimum_tenure_months=12,
        maximum_tenure_months=360,
        typical_tenure_months=240,
        interest_rate_min=8.25,
        interest_rate_max=10.50,
        interest_rate_current=8.75,
        annual_percentage_rate=9.00,
        processing_fee_value=0.50,
        processing_fee_min=3000,
        processing_fee_max=10000,
        prepayment_charge=0,
        foreclosure_charge=0,
        minimum_age=21,
        maximum_age=65,
        minimum_income_monthly=25000,
        minimum_income_annual=300000,
        minimum_credit_score=700,
        co_applicant_allowed="Yes",
        co_applicant_required="No",
        maximum_co_applicants=2,
        collateral_required="Yes",
        collateral_type="Residential Property",
        security_type="Mortgage",
        mortgage_required="Yes",
        collateral_value_required=1000000,
        collateral_valuation_method="Bank-approved valuation",
        property_document_required="Yes",
        full_disbursement_allowed="Yes",
        partial_disbursement_allowed="Yes",
        multiple_disbursement_allowed="Yes",
        estimated_disbursement_time="7-15 working days",
        moratorium_available="Yes",
        moratorium_period_months=24,
        tax_benefit_available="Yes",
        digital_application_available="Yes",
        relationship_manager_service="Yes",
        tag_home=1,
        tag_property=1,
        tag_high_value=1,
        tag_premium=1
    ),

    # ========================================================
    # HOME BALANCE TRANSFER
    # ========================================================

    create_loan(
        "LN003",
        "HDFC_HOME_BALANCE_TRANSFER",
        "Home Loan Balance Transfer",
        "Home",
        "Balance Transfer",
        "Home Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Transfer existing home loan",
        allowed_purposes="Transfer existing housing loan",
        balance_transfer_available="Yes",
        top_up_available="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=100000000,
        minimum_tenure_months=12,
        maximum_tenure_months=240,
        typical_tenure_months=180,
        interest_rate_min=8.25,
        interest_rate_max=10.25,
        interest_rate_current=8.75,
        processing_fee_value=0.50,
        prepayment_allowed="Yes",
        foreclosure_allowed="Yes",
        collateral_required="Yes",
        collateral_type="Residential Property",
        security_type="Mortgage",
        mortgage_required="Yes",
        minimum_income_monthly=30000,
        minimum_income_annual=360000,
        minimum_credit_score=700,
        tax_benefit_available="Yes",
        tag_home=1,
        tag_property=1,
        tag_high_value=1
    ),

    # ========================================================
    # LOAN AGAINST PROPERTY
    # ========================================================

    create_loan(
        "LN004",
        "HDFC_LOAN_AGAINST_PROPERTY",
        "Loan Against Property",
        "Property",
        "Mortgage Loan",
        "Loan Against Property",
        secured_or_unsecured="Secured",
        loan_purpose="Personal or business financing against property",
        allowed_purposes="Business expansion, personal needs, education, medical and other permitted purposes",
        working_capital_financing="Yes",
        refinancing_available="Yes",
        top_up_available="Yes",
        minimum_loan_amount=1000000,
        maximum_loan_amount=100000000,
        minimum_tenure_months=12,
        maximum_tenure_months=180,
        typical_tenure_months=120,
        interest_rate_min=9.50,
        interest_rate_max=13.50,
        interest_rate_current=10.50,
        processing_fee_value=1,
        collateral_required="Yes",
        collateral_type="Residential / Commercial Property",
        security_type="Mortgage",
        mortgage_required="Yes",
        collateral_value_required=2000000,
        collateral_valuation_method="Bank-approved property valuation",
        minimum_income_monthly=50000,
        minimum_income_annual=600000,
        minimum_credit_score=700,
        property_document_required="Yes",
        business_proof_required="Yes",
        tag_property=1,
        tag_business=1,
        tag_high_value=1,
        tag_premium=1
    ),

    # ========================================================
    # CAR
    # ========================================================

    create_loan(
        "LN005",
        "HDFC_NEW_CAR_LOAN",
        "New Car Loan",
        "Auto",
        "New Car Finance",
        "Auto Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase of new car",
        allowed_purposes="New passenger vehicle",
        end_use_restriction="Vehicle purchase only",
        asset_financing="Yes",
        refinancing_available="No",
        minimum_loan_amount=100000,
        maximum_loan_amount=10000000,
        minimum_down_payment=10,
        maximum_financing_percentage=90,
        loan_to_value_ratio=90,
        margin_requirement=10,
        minimum_tenure_months=12,
        maximum_tenure_months=84,
        typical_tenure_months=60,
        interest_rate_min=8.50,
        interest_rate_max=13.00,
        interest_rate_current=9.25,
        processing_fee_value=0.50,
        prepayment_charge=2,
        foreclosure_charge=2,
        minimum_income_monthly=30000,
        minimum_income_annual=360000,
        minimum_credit_score=700,
        collateral_required="Yes",
        collateral_type="Vehicle",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        vehicle_type="Car",
        vehicle_condition="New",
        tag_vehicle=1,
        tag_high_value=1
    ),

    # ========================================================
    # USED CAR
    # ========================================================

    create_loan(
        "LN006",
        "HDFC_USED_CAR_LOAN",
        "Used Car Loan",
        "Auto",
        "Used Car Finance",
        "Auto Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase of used car",
        asset_financing="Yes",
        minimum_loan_amount=100000,
        maximum_loan_amount=5000000,
        minimum_down_payment=20,
        maximum_financing_percentage=80,
        loan_to_value_ratio=80,
        minimum_tenure_months=12,
        maximum_tenure_months=84,
        typical_tenure_months=60,
        interest_rate_min=10.00,
        interest_rate_max=16.00,
        interest_rate_current=11.50,
        processing_fee_value=1,
        prepayment_charge=3,
        minimum_income_monthly=30000,
        minimum_income_annual=360000,
        minimum_credit_score=700,
        collateral_required="Yes",
        collateral_type="Used Vehicle",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        vehicle_type="Car",
        vehicle_condition="Used",
        valuation_charge=1000,
        tag_vehicle=1
    ),

    # ========================================================
    # TWO WHEELER
    # ========================================================

    create_loan(
        "LN007",
        "HDFC_TWO_WHEELER_LOAN",
        "Two-Wheeler Loan",
        "Two-Wheeler",
        "Bike / Scooter Finance",
        "Two-Wheeler Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase of two-wheeler",
        allowed_purposes="New two-wheeler",
        asset_financing="Yes",
        minimum_loan_amount=20000,
        maximum_loan_amount=1000000,
        minimum_down_payment=10,
        maximum_financing_percentage=90,
        loan_to_value_ratio=90,
        minimum_tenure_months=12,
        maximum_tenure_months=60,
        typical_tenure_months=36,
        interest_rate_min=10.00,
        interest_rate_max=18.00,
        interest_rate_current=12.00,
        processing_fee_value=1,
        minimum_income_monthly=15000,
        minimum_income_annual=180000,
        minimum_credit_score=680,
        collateral_required="Yes",
        collateral_type="Two-Wheeler",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        vehicle_type="Two-Wheeler",
        vehicle_condition="New",
        tag_two_wheeler=1,
        tag_vehicle=1
    ),

    # ========================================================
    # EDUCATION
    # ========================================================

    create_loan(
        "LN008",
        "HDFC_EDUCATION_LOAN",
        "Education Loan",
        "Education",
        "Higher Education Loan",
        "Education Loan",
        secured_or_unsecured="Secured / Unsecured",
        loan_purpose="Higher education financing",
        allowed_purposes="Tuition, hostel, examination fees, books, equipment and permitted education expenses",
        minimum_loan_amount=50000,
        maximum_loan_amount=7500000,
        minimum_tenure_months=36,
        maximum_tenure_months=180,
        typical_tenure_months=120,
        repayment_frequency="Monthly",
        grace_period_days=0,
        moratorium_period_months=12,
        interest_rate_min=9.00,
        interest_rate_max=14.00,
        interest_rate_current=10.50,
        processing_fee_value=0,
        prepayment_charge=0,
        minimum_age=18,
        maximum_age=35,
        minimum_income_monthly=25000,
        minimum_income_annual=300000,
        minimum_credit_score=650,
        credit_history_required="No",
        co_applicant_allowed="Yes",
        co_applicant_required="Yes",
        minimum_co_applicants=1,
        maximum_co_applicants=2,
        guarantor_required="No",
        acceptable_co_applicant_relationships="Parent / Guardian",
        co_applicant_income_considered="Yes",
        salaried_eligible="Yes",
        self_employed_eligible="Yes",
        business_owner_eligible="Yes",
        professional_eligible="Yes",
        student_eligible="Yes",
        income_document_required="Yes",
        bank_statement_months_required=6,
        salary_slip_months_required=3,
        itr_years_required=2,
        collateral_required="Conditional",
        collateral_type="Property / Financial Security",
        security_type="Mortgage / Guarantee",
        property_document_required="Conditional",
        education_document_required="Yes",
        institution_type="Recognized Institution",
        course_type="Degree / Diploma / Professional Course",
        digital_application_available="Yes",
        moratorium_available="Yes",
        tax_benefit_available="Yes",
        tag_education=1,
        tag_professional=1
    ),

    # ========================================================
    # GOLD
    # ========================================================

    create_loan(
        "LN009",
        "HDFC_GOLD_LOAN",
        "Gold Loan",
        "Gold",
        "Gold-backed Loan",
        "Gold Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Short-term financial requirements against gold",
        allowed_purposes="Personal, medical, education and permitted financial requirements",
        minimum_loan_amount=10000,
        maximum_loan_amount=5000000,
        minimum_down_payment=0,
        maximum_financing_percentage=75,
        loan_to_value_ratio=75,
        margin_requirement=25,
        minimum_tenure_months=3,
        maximum_tenure_months=36,
        typical_tenure_months=12,
        interest_rate_min=9.00,
        interest_rate_max=18.00,
        interest_rate_current=11.00,
        processing_fee_value=1,
        prepayment_charge=0,
        foreclosure_charge=0,
        minimum_age=18,
        maximum_age=65,
        minimum_income_monthly=10000,
        minimum_income_annual=120000,
        minimum_credit_score=0,
        credit_history_required="No",
        collateral_required="Yes",
        collateral_type="Gold Jewellery / Gold Assets",
        security_type="Pledge",
        pledge_required="Yes",
        collateral_value_required=50000,
        collateral_valuation_method="Approved gold valuation",
        gold_document_required="Yes",
        gold_purity_requirement=18,
        gold_valuation_method="Purity and market value",
        documentation_charge=100,
        valuation_charge=100,
        disbursement_mode="Bank Account Transfer",
        estimated_disbursement_time="Same day",
        digital_application_available="Yes",
        instant_approval_available="Yes",
        tag_gold=1,
        tag_emergency=1,
        tag_quick_disbursal=1,
        tag_low_documentation=1
    ),

    # ========================================================
    # CONSUMER DURABLE
    # ========================================================

    create_loan(
        "LN010",
        "HDFC_CONSUMER_DURABLE_LOAN",
        "Consumer Durable Loan",
        "Consumer",
        "Consumer Durable Finance",
        "Consumer Durable Loan",
        secured_or_unsecured="Unsecured",
        loan_purpose="Purchase of consumer electronics and appliances",
        allowed_purposes="Television, refrigerator, laptop, mobile, appliances and electronics",
        minimum_loan_amount=10000,
        maximum_loan_amount=500000,
        minimum_tenure_months=3,
        maximum_tenure_months=36,
        typical_tenure_months=12,
        interest_rate_min=0,
        interest_rate_max=18,
        interest_rate_current=12,
        annual_percentage_rate=12.00,
        processing_fee_value=0,
        prepayment_charge=0,
        minimum_age=21,
        maximum_age=65,
        minimum_income_monthly=15000,
        minimum_income_annual=180000,
        minimum_credit_score=680,
        collateral_required="No",
        digital_application_available="Yes",
        instant_approval_available="Yes",
        paperless_processing="Yes",
        tag_digital=1,
        tag_quick_disbursal=1,
        tag_low_documentation=1
    ),

    # ========================================================
    # BUSINESS LOAN
    # ========================================================

    create_loan(
        "LN011",
        "HDFC_BUSINESS_LOAN",
        "Business Loan",
        "Business",
        "Unsecured Business Loan",
        "Business Loan",
        customer_type="Business",
        secured_or_unsecured="Unsecured",
        loan_purpose="Business expansion and working capital",
        allowed_purposes="Working capital, expansion, equipment and business requirements",
        working_capital_financing="Yes",
        refinancing_available="Yes",
        top_up_available="Yes",
        minimum_loan_amount=100000,
        maximum_loan_amount=5000000,
        minimum_tenure_months=12,
        maximum_tenure_months=60,
        typical_tenure_months=36,
        interest_rate_min=11,
        interest_rate_max=24,
        interest_rate_current=14,
        processing_fee_value=2,
        minimum_age=21,
        maximum_age=65,
        minimum_income_annual=500000,
        minimum_turnover=1000000,
        minimum_net_profit=200000,
        minimum_credit_score=700,
        minimum_business_vintage_months=36,
        business_proof_required="Yes",
        itr_required="Yes",
        itr_years_required=3,
        collateral_required="No",
        digital_application_available="Yes",
        relationship_manager_service="Yes",
        tag_business=1,
        tag_small_business=1,
        tag_high_value=1
    ),

    # ========================================================
    # WORKING CAPITAL
    # ========================================================

    create_loan(
        "LN012",
        "HDFC_WORKING_CAPITAL",
        "Working Capital Finance",
        "Business",
        "Working Capital",
        "Working Capital Loan",
        customer_type="Business",
        secured_or_unsecured="Secured",
        loan_purpose="Business working capital",
        allowed_purposes="Inventory, receivables, operating expenses and working capital",
        working_capital_financing="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=50000000,
        minimum_tenure_months=12,
        maximum_tenure_months=60,
        typical_tenure_months=36,
        interest_rate_min=9.5,
        interest_rate_max=15,
        interest_rate_current=11,
        processing_fee_value=1,
        minimum_age=21,
        maximum_age=70,
        minimum_turnover=5000000,
        minimum_net_profit=500000,
        minimum_credit_score=700,
        minimum_business_vintage_months=36,
        collateral_required="Yes",
        collateral_type="Business Assets / Property",
        security_type="Charge / Mortgage",
        mortgage_required="Conditional",
        collateral_value_required=1000000,
        collateral_valuation_method="Bank-approved valuation",
        business_proof_required="Yes",
        itr_required="Yes",
        itr_years_required=3,
        relationship_manager_service="Yes",
        tag_business=1,
        tag_small_business=1,
        tag_high_value=1
    ),

    # ========================================================
    # AGRICULTURE
    # ========================================================

    create_loan(
        "LN013",
        "HDFC_AGRI_TRACTOR",
        "Agriculture and Tractor Loan",
        "Agriculture",
        "Tractor Finance",
        "Agriculture Loan",
        secured_or_unsecured="Secured",
        loan_purpose="Agricultural equipment and tractor purchase",
        allowed_purposes="Tractor, farm equipment and agriculture activities",
        asset_financing="Yes",
        minimum_loan_amount=50000,
        maximum_loan_amount=2500000,
        minimum_down_payment=10,
        maximum_financing_percentage=90,
        loan_to_value_ratio=90,
        minimum_tenure_months=12,
        maximum_tenure_months=84,
        typical_tenure_months=60,
        interest_rate_min=9,
        interest_rate_max=15,
        interest_rate_current=11,
        processing_fee_value=1,
        minimum_age=18,
        maximum_age=70,
        minimum_income_annual=150000,
        collateral_required="Yes",
        collateral_type="Agricultural Asset / Tractor",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        agriculture_activity="Agriculture / Dairy / Farming",
        business_proof_required="Yes",
        tag_agriculture=1,
        tag_vehicle=1
    ),

    # ========================================================
    # HEALTHCARE
    # ========================================================

    create_loan(
        "LN014",
        "HDFC_HEALTHCARE_FINANCE",
        "Healthcare Finance",
        "Healthcare",
        "Medical / Healthcare Business Finance",
        "Healthcare Loan",
        customer_type="Business",
        secured_or_unsecured="Secured / Unsecured",
        loan_purpose="Healthcare infrastructure and equipment",
        allowed_purposes="Hospital expansion, medical equipment, clinic setup",
        asset_financing="Yes",
        working_capital_financing="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=50000000,
        minimum_tenure_months=12,
        maximum_tenure_months=120,
        typical_tenure_months=60,
        interest_rate_min=9,
        interest_rate_max=16,
        interest_rate_current=11.5,
        processing_fee_value=1,
        minimum_income_annual=1000000,
        minimum_turnover=5000000,
        minimum_business_vintage_months=36,
        minimum_credit_score=700,
        collateral_required="Conditional",
        collateral_type="Property / Equipment",
        security_type="Mortgage / Hypothecation",
        business_proof_required="Yes",
        other_documents="Professional registration and healthcare permits",
        business_sector="Healthcare",
        professional_eligible="Yes",
        tag_medical=1,
        tag_business=1,
        tag_professional=1
    ),

    # ========================================================
    # COMMERCIAL VEHICLE
    # ========================================================

    create_loan(
        "LN015",
        "HDFC_COMMERCIAL_VEHICLE",
        "Commercial Vehicle Finance",
        "Commercial",
        "Commercial Vehicle Loan",
        "Commercial Vehicle Loan",
        customer_type="Business",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase of commercial vehicle",
        allowed_purposes="Goods vehicles, buses, taxis and commercial transport",
        asset_financing="Yes",
        minimum_loan_amount=200000,
        maximum_loan_amount=10000000,
        minimum_down_payment=15,
        maximum_financing_percentage=85,
        loan_to_value_ratio=85,
        minimum_tenure_months=12,
        maximum_tenure_months=84,
        typical_tenure_months=60,
        interest_rate_min=9,
        interest_rate_max=16,
        interest_rate_current=11.5,
        processing_fee_value=1,
        minimum_age=21,
        maximum_age=70,
        minimum_income_annual=500000,
        minimum_turnover=2000000,
        minimum_business_vintage_months=24,
        minimum_credit_score=700,
        collateral_required="Yes",
        collateral_type="Commercial Vehicle",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        commercial_vehicle_type="Truck / Bus / Taxi / Commercial Vehicle",
        business_proof_required="Yes",
        tag_vehicle=1,
        tag_business=1,
        tag_high_value=1
    ),

    # ========================================================
    # CONSTRUCTION EQUIPMENT
    # ========================================================

    create_loan(
        "LN016",
        "HDFC_CONSTRUCTION_EQUIPMENT",
        "Construction Equipment Finance",
        "Commercial",
        "Construction Equipment",
        "Equipment Loan",
        customer_type="Business",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase construction equipment",
        allowed_purposes="Excavators, loaders, cranes and construction equipment",
        asset_financing="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=50000000,
        minimum_down_payment=20,
        maximum_financing_percentage=80,
        loan_to_value_ratio=80,
        minimum_tenure_months=12,
        maximum_tenure_months=84,
        typical_tenure_months=60,
        interest_rate_min=9.5,
        interest_rate_max=16,
        interest_rate_current=12,
        processing_fee_value=1,
        minimum_income_annual=1000000,
        minimum_turnover=5000000,
        minimum_business_vintage_months=36,
        minimum_credit_score=700,
        collateral_required="Yes",
        collateral_type="Construction Equipment",
        security_type="Hypothecation",
        hypothecation_required="Yes",
        vehicle_document_required="Yes",
        construction_equipment_type="Heavy Equipment / Machinery",
        business_proof_required="Yes",
        tag_business=1,
        tag_high_value=1
    ),

    # ========================================================
    # LOAN AGAINST SECURITIES
    # ========================================================

    create_loan(
        "LN017",
        "HDFC_LOAN_AGAINST_SECURITIES",
        "Loan Against Securities",
        "Investment",
        "Securities-backed Loan",
        "Loan Against Securities",
        secured_or_unsecured="Secured",
        loan_purpose="Liquidity against eligible investments",
        allowed_purposes="Permitted personal and business liquidity needs",
        minimum_loan_amount=100000,
        maximum_loan_amount=10000000,
        minimum_tenure_months=1,
        maximum_tenure_months=36,
        typical_tenure_months=12,
        interest_rate_min=9,
        interest_rate_max=13,
        interest_rate_current=10,
        processing_fee_value=0.5,
        minimum_credit_score=0,
        credit_history_required="Not Mandatory",
        collateral_required="Yes",
        collateral_type="Shares / Bonds / Securities",
        security_type="Pledge",
        pledge_required="Yes",
        lien_required="Yes",
        collateral_value_required=500000,
        collateral_valuation_method="Market value with applicable haircut",
        digital_application_available="Yes",
        tag_investment=1,
        tag_premium=1,
        tag_high_value=1
    ),

    # ========================================================
    # LOAN AGAINST MUTUAL FUNDS
    # ========================================================

    create_loan(
        "LN018",
        "HDFC_DIGITAL_LOAN_AGAINST_MUTUAL_FUNDS",
        "Digital Loan Against Mutual Funds",
        "Investment",
        "Mutual Fund-backed Loan",
        "Loan Against Mutual Funds",
        secured_or_unsecured="Secured",
        loan_purpose="Liquidity against mutual fund holdings",
        minimum_loan_amount=50000,
        maximum_loan_amount=5000000,
        minimum_tenure_months=1,
        maximum_tenure_months=12,
        typical_tenure_months=6,
        interest_rate_min=9,
        interest_rate_max=14,
        interest_rate_current=10.5,
        processing_fee_value=0.5,
        credit_history_required="Not Mandatory",
        collateral_required="Yes",
        collateral_type="Mutual Fund Units",
        security_type="Lien / Pledge",
        pledge_required="Yes",
        lien_required="Yes",
        collateral_value_required=100000,
        collateral_valuation_method="NAV with applicable haircut",
        digital_application_available="Yes",
        instant_approval_available="Yes",
        paperless_processing="Yes",
        tag_investment=1,
        tag_digital=1,
        tag_quick_disbursal=1,
        tag_premium=1
    ),

    # ========================================================
    # INFRASTRUCTURE
    # ========================================================

    create_loan(
        "LN019",
        "HDFC_INFRASTRUCTURE_FINANCE",
        "Infrastructure Finance",
        "Corporate",
        "Infrastructure Project Finance",
        "Infrastructure Loan",
        customer_type="Corporate",
        secured_or_unsecured="Secured",
        loan_purpose="Infrastructure project financing",
        allowed_purposes="Roads, power, utilities, infrastructure projects",
        working_capital_financing="Yes",
        minimum_loan_amount=50000000,
        maximum_loan_amount=5000000000,
        minimum_tenure_months=60,
        maximum_tenure_months=240,
        typical_tenure_months=120,
        interest_rate_min=8,
        interest_rate_max=13,
        interest_rate_current=10,
        processing_fee_value=0.5,
        minimum_income_annual=10000000,
        minimum_turnover=50000000,
        minimum_net_profit=5000000,
        minimum_credit_score=750,
        minimum_business_vintage_months=60,
        co_applicant_allowed="Yes",
        collateral_required="Yes",
        collateral_type="Project Assets / Property",
        security_type="Mortgage / Charge",
        mortgage_required="Yes",
        business_proof_required="Yes",
        business_sector="Infrastructure",
        tag_business=1,
        tag_high_value=1,
        tag_premium=1
    ),

    # ========================================================
    # NRI HOME LOAN
    # ========================================================

    create_loan(
        "LN020",
        "HDFC_NRI_HOME_LOAN",
        "NRI Home Loan",
        "Home",
        "NRI Residential Home Loan",
        "Home Loan",
        customer_type="NRI",
        secured_or_unsecured="Secured",
        loan_purpose="Purchase or construction of residential property in India",
        allowed_purposes="Residential property purchase / construction",
        asset_financing="Yes",
        balance_transfer_available="Yes",
        top_up_available="Yes",
        minimum_loan_amount=500000,
        maximum_loan_amount=100000000,
        minimum_down_payment=20,
        maximum_financing_percentage=80,
        loan_to_value_ratio=80,
        minimum_tenure_months=12,
        maximum_tenure_months=240,
        typical_tenure_months=180,
        interest_rate_min=8.5,
        interest_rate_max=11,
        interest_rate_current=9,
        processing_fee_value=0.5,
        minimum_age=21,
        maximum_age=60,
        minimum_income_annual=1000000,
        minimum_credit_score=700,
        residential_requirement="NRI / OCI",
        citizenship_requirement="Indian Citizen / OCI",
        co_applicant_allowed="Yes",
        co_applicant_required="Conditional",
        collateral_required="Yes",
        collateral_type="Residential Property",
        security_type="Mortgage",
        mortgage_required="Yes",
        property_document_required="Yes",
        collateral_valuation_method="Bank-approved valuation",
        digital_application_available="Yes",
        relationship_manager_service="Yes",
        tag_home=1,
        tag_property=1,
        tag_nri=1,
        tag_high_value=1
    )
]


# ============================================================
# FIELD LIST
# ============================================================

FIELDNAMES = [
    "loan_product_id",
    "product_code",
    "product_name",
    "loan_category",
    "loan_subcategory",
    "loan_type",
    "customer_type",
    "secured_or_unsecured",
    "product_status",
    "product_description",

    "loan_purpose",
    "allowed_purposes",
    "end_use_restriction",
    "asset_financing",
    "working_capital_financing",
    "refinancing_available",
    "balance_transfer_available",
    "top_up_available",
    "additional_loan_available",

    "minimum_loan_amount",
    "maximum_loan_amount",
    "minimum_loan_amount_online",
    "maximum_loan_amount_online",
    "minimum_down_payment",
    "maximum_financing_percentage",
    "loan_to_value_ratio",
    "margin_requirement",

    "minimum_tenure_months",
    "maximum_tenure_months",
    "typical_tenure_months",
    "repayment_frequency",
    "grace_period_days",
    "moratorium_period_months",

    "interest_rate_type",
    "interest_rate_min",
    "interest_rate_max",
    "interest_rate_current",
    "annual_percentage_rate",
    "benchmark_rate",
    "spread",
    "fixed_rate_available",
    "floating_rate_available",
    "rate_reset_frequency",

    "processing_fee_type",
    "processing_fee_value",
    "processing_fee_min",
    "processing_fee_max",
    "prepayment_allowed",
    "prepayment_charge_type",
    "prepayment_charge",
    "foreclosure_allowed",
    "foreclosure_charge",
    "part_payment_allowed",
    "part_payment_charge",
    "late_payment_fee",
    "bounce_charge",
    "penal_interest",
    "documentation_charge",
    "stamp_duty_charge",
    "valuation_charge",
    "legal_charge",
    "insurance_charge",
    "other_charges",

    "minimum_age",
    "maximum_age",
    "minimum_age_at_maturity",
    "maximum_age_at_maturity",
    "residential_requirement",
    "citizenship_requirement",
    "employment_type",
    "allowed_employment_types",
    "minimum_work_experience_months",
    "minimum_business_vintage_months",
    "minimum_income_monthly",
    "minimum_income_annual",
    "minimum_turnover",
    "minimum_net_profit",
    "minimum_credit_score",
    "credit_history_required",
    "existing_customer_required",
    "bank_account_required",
    "relationship_duration_required_months",

    "co_applicant_allowed",
    "co_applicant_required",
    "minimum_co_applicants",
    "maximum_co_applicants",
    "guarantor_required",
    "acceptable_co_applicant_relationships",
    "co_applicant_income_considered",

    "salaried_eligible",
    "self_employed_eligible",
    "business_owner_eligible",
    "professional_eligible",
    "government_employee_eligible",
    "retired_eligible",
    "student_eligible",
    "minimum_employment_months",
    "minimum_business_vintage_years",
    "income_document_required",
    "bank_statement_months_required",
    "salary_slip_months_required",
    "itr_years_required",

    "credit_score_required",
    "maximum_dti_ratio",
    "maximum_foir_ratio",
    "existing_loan_allowed",
    "existing_loan_limit",
    "credit_card_history_required",
    "delinquency_allowed",
    "maximum_recent_enquiries",

    "collateral_required",
    "collateral_type",
    "security_type",
    "hypothecation_required",
    "mortgage_required",
    "pledge_required",
    "lien_required",
    "guarantee_required",
    "collateral_value_required",
    "collateral_valuation_method",

    "identity_proof_required",
    "address_proof_required",
    "income_proof_required",
    "bank_statement_required",
    "salary_slip_required",
    "itr_required",
    "employment_proof_required",
    "business_proof_required",
    "property_document_required",
    "vehicle_document_required",
    "gold_document_required",
    "education_document_required",
    "collateral_document_required",
    "other_documents",

    "disbursement_mode",
    "disbursement_account_required",
    "minimum_disbursement_amount",
    "maximum_disbursement_amount",
    "full_disbursement_allowed",
    "partial_disbursement_allowed",
    "multiple_disbursement_allowed",
    "estimated_disbursement_time",

    "emi_available",
    "emi_frequency",
    "emi_start_month",
    "repayment_method",
    "auto_debit_available",
    "nach_available",
    "ecs_available",
    "digital_repayment_available",
    "advance_emi_allowed",
    "moratorium_available",

    "asset_type",
    "vehicle_type",
    "vehicle_condition",
    "property_type",
    "property_location_requirement",
    "education_level",
    "education_country",
    "institution_type",
    "course_type",
    "gold_purity_requirement",
    "gold_valuation_method",
    "business_sector",
    "agriculture_activity",
    "commercial_vehicle_type",
    "construction_equipment_type",

    "digital_application_available",
    "instant_approval_available",
    "pre_approved_available",
    "paperless_processing",
    "doorstep_service",
    "relationship_manager_service",
    "flexible_repayment",
    "step_up_emi_available",
    "step_down_emi_available",
    "balloon_payment_available",
    "seasonal_repayment_available",
    "tax_benefit_available",
    "insurance_bundle_available",
    "special_rate_available",
    "promotional_offer_available",

    "tag_personal",
    "tag_home",
    "tag_vehicle",
    "tag_two_wheeler",
    "tag_education",
    "tag_travel",
    "tag_medical",
    "tag_business",
    "tag_agriculture",
    "tag_gold",
    "tag_property",
    "tag_investment",
    "tag_emergency",
    "tag_small_business",
    "tag_professional",
    "tag_nri",
    "tag_premium",
    "tag_digital",
    "tag_quick_disbursal",
    "tag_low_documentation",
    "tag_high_value",

    "launch_date",
    "end_date",
    "created_at",
    "updated_at"
]


# ============================================================
# VALIDATE
# ============================================================

def validate(rows, fields):
    for row_number, row in enumerate(rows, start=1):
        for field in fields:

            if field not in row:
                raise ValueError(
                    f"Missing field '{field}' in row {row_number}"
                )

            value = row[field]

            if value is None:
                raise ValueError(
                    f"None value in row {row_number}, field '{field}'"
                )

            if isinstance(value, str) and value.strip() == "":
                raise ValueError(
                    f"Blank value in row {row_number}, field '{field}'"
                )


validate(loans, FIELDNAMES)


# ============================================================
# WRITE CSV
# ============================================================

with open(
    OUTPUT_FILE,
    "w",
    newline="",
    encoding="utf-8"
) as file:

    writer = csv.DictWriter(
        file,
        fieldnames=FIELDNAMES
    )

    writer.writeheader()
    writer.writerows(loans)


# ============================================================
# SUMMARY
# ============================================================

print("=" * 70)
print("LOAN PRODUCT DATA GENERATED")
print("=" * 70)

print(f"Products generated : {len(loans)}")
print(f"Columns            : {len(FIELDNAMES)}")
print(f"Blank values       : 0")
print(f"Output file        : {OUTPUT_FILE}")

print("\nProducts:")

for row in loans:
    print(
        f"{row['loan_product_id']} | "
        f"{row['product_name']} | "
        f"{row['loan_category']}"
    )

print("=" * 70)