"""Pydantic models for the Phase 6 request/response contracts."""

from app.models.personalization import (
    Channel,
    ChannelContent,
    DecisionContext,
    EligibilityStatus,
    EmailContent,
    GenerationMetadata,
    GenerationResponse,
    InAppContent,
    OwnershipStatus,
    PersonalizationRequest,
    Preferences,
    ProductFamily,
    PushContent,
    RecentEvent,
    RecommendedProduct,
    RelationshipManagerContent,
    SmsContent,
    ValidationInfo,
    ValidationStatus,
)
from app.models.product import (
    CreditCardProduct,
    GroundedFact,
    GroundedFactCategory,
    GroundedProductFacts,
    ProductStatus,
)
from app.models.prompt import PromptPackage
from app.models.generation import GeneratedContent
from app.models.validation import ValidationResult, Violation, ViolationCode

__all__ = [
    "Channel",
    "ChannelContent",
    "CreditCardProduct",
    "DecisionContext",
    "EligibilityStatus",
    "EmailContent",
    "GenerationMetadata",
    "GenerationResponse",
    "GroundedFact",
    "GroundedFactCategory",
    "GeneratedContent",
    "GroundedProductFacts",
    "InAppContent",
    "OwnershipStatus",
    "PersonalizationRequest",
    "Preferences",
    "ProductFamily",
    "ProductStatus",
    "PromptPackage",
    "PushContent",
    "RecentEvent",
    "RecommendedProduct",
    "RelationshipManagerContent",
    "SmsContent",
    "ValidationInfo",
    "ValidationResult",
    "ValidationStatus",
    "Violation",
    "ViolationCode",
]
